### ISSUE TITLE
Hey Oren.

### ISSUE THREAD

**Issue by floer32** [orenmazor/Dada-Engine#3]
We should talk about generative text sometime.

**Comment by floer32** [comment]
Table.

**Comment by orenmazor** [comment]
most creative way to "slip into my inbox" in months.

**Comment by hangtwenty** [comment]
What can I say, I was born slippy

**Comment by hangtwenty** [comment]
That's not a frog thing it's a house music thing

**Comment by floer32** [comment]
| Thing      | Is Just A   |
|------------|-------------|
| Your inbox | Table       |
| CSS Grid   | Table       |
| Netflix    | Table       |
| Flipping   | Table       |
| Slipping   | Way of life |
